</active-response>

<command>
    <name>firewall-drop</name>
    <executable>firewall-drop</executable>
    <expect>srcip</expect>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  <active-response>
    <command>firewall-drop</command>
    <location>local</location>
    <rules_id>31103,31106,31151</rules_id>
    <timeout>10</timeout>
  </active-response>

  <command>
    <name>wall-alert</name>
    <executable>wall</executable>
    <expect>srcip</expect>
  </command>

  <active-response>
    <command>wall-alert</command>
    <location>all</location>
    <level>3</level>